### ISSUE TITLE
Shouldn't you cite your source? Your tutorial, too

### ISSUE THREAD

**Issue by rrshaban** [erikwco/sinatra-warden-template#1]
http://sklise.com/2013/03/08/sinatra-warden-auth/

Seems only respectful.

**Comment by erikwco** [comment]
Hi rrshaban, believe me if I had followed and taken the code from that link, it would put the reference, but if you think it is so, I can add the link, no problem

**Comment by erikwco** [comment]
done!  @rrshaban 

:+1:
